/// @file hooks.hpp
/// @brief Contains convenience macros to create hooks and register for user-initiated
/// installation at a later time with the INSTALL_EARLY_HOOKS and INSTALL_LATE_HOOKS macros
/// or automatically installed on dlopen.
///
/// IMPORTANT: This file is automatically generated.
/// Do not edit this file directly. Any changes made to this file will be overwritten.
/// Please modify the make-hooking script that generates this file instead.

#pragma once
#include "beatsaber-hook/shared/hooking.hpp"

/// @brief This namespace is internal to the AutoHooks library and should not be used directly.
/// Anything in this namespace is not part of the public API.  Use the macros provided.
namespace __AutoHooksInternal__ {
    /**
     * @brief The DeferredHooks class manages the registration and installation of
     * hook functions.
     *
     * This class provides a mechanism to register hook installation functions that
     * can be called later to install hooks. It maintains a list of installation
     * functions and provides methods to add to this list and to call all registered
     * functions at a later time.
     */
    class DeferredHooks {
       public:
        /// @brief The HookType enum class represents the type of hook.
        enum class HookType { Early, Late };

       private:
        /// @brief Returns the list of hook installation functions for the specified type.
        /// @param type The type of hooks to get the installation functions for.
        /// @return A reference to the list of installation functions.
        inline static std::vector<void (*)()>& getInstallFuncs(HookType type) {
            switch (type) {
                case ::__AutoHooksInternal__::DeferredHooks::HookType::Early:
                    static std::vector<void (*)()> earlyInstallFuncs;
                    return earlyInstallFuncs;

                case ::__AutoHooksInternal__::DeferredHooks::HookType::Late:
                    static std::vector<void (*)()> lateInstallFuncs;
                    return lateInstallFuncs;
            }
        }

       public:
        /// @brief A logger context for the DeferredHooks class.
        inline static constexpr auto logger = Paper::ConstLoggerContext(MOD_ID);

        /// @brief Adds a hook installation function to the specified list.
        /// @param type The type of hook to add the installation function to.
        /// @param installFunc The installation function to add.
        inline static void addInstallFunc(HookType type, void (*installFunc)()) {
            getInstallFuncs(type).push_back(installFunc);
        }

        /// @brief Calls all installation functions added via addInstallFunc and
        /// then clears the list.
        /// @param type The type of hooks to install.
        inline static void installHooks(HookType type) {
            auto installFuncs = getInstallFuncs(type);

            for (auto& func : installFuncs) {
                func();
            }

            // Why would we need to keep these around?
            installFuncs.clear();
        }

        /// @brief Returns the number of hook installation functions that have
        /// been registered for the specified type.
        inline static int getHookCount(HookType type) {
            return getInstallFuncs(type).size();
        }
    };
}  // namespace __AutoHooksInternal__

/// AutoHooks Macros
namespace {

/// @brief Macro to automatically register a deferred early hook installation
/// function.
/// @param name_ The name of the hook to be installed.
#define MAKE_EARLY_HOOK_INSTALL_WITH_AUTOLOGGER(name_)                                                                         \
    __attribute((constructor)) void Hook_##name_##_Auto_Register() {                                                           \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Early, []() { \
            INSTALL_HOOK(::__AutoHooksInternal__::DeferredHooks::logger, name_);                                               \
        });                                                                                                                    \
    }

/// @brief Macro to automatically register a deferred early hook installation
/// function for original hooks.
/// @param name_ The name of the hook to be installed.
#define MAKE_EARLY_ORIG_HOOK_INSTALL_WITH_AUTOLOGGER(name_)                                                                    \
    __attribute((constructor)) void Hook_##name_##_Auto_Orig_Register() {                                                      \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Early, []() { \
            INSTALL_HOOK_ORIG(::__AutoHooksInternal__::DeferredHooks::logger, name_);                                          \
        });                                                                                                                    \
    }

/// @brief Macro to automatically register a deferred early direct hook
/// installation function.
/// @param name_ The name of the hook to be installed.
/// @param addr_ The address that should be hooked.
#define MAKE_EARLY_DIRECT_HOOK_INSTALL_WITH_AUTOLOGGER(name_, addr_)                                                           \
    __attribute((constructor)) void Hook_##name_##_Auto_Register() {                                                           \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Early, []() { \
            INSTALL_HOOK_DIRECT(::__AutoHooksInternal__::DeferredHooks::logger, name_, addr_);                                 \
        });                                                                                                                    \
    }

/// @brief Macro to automatically register a deferred early hook installation
/// function with specified logger.
/// @param logger_ The logger to be used during install.
/// @param name_ The name of the hook to be installed.
#define MAKE_EARLY_HOOK_INSTALL(logger_, name_)                                                                                \
    __attribute((constructor)) void Hook_##name_##_Auto_Register() {                                                           \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Early, []() { \
            INSTALL_HOOK(logger_, name_);                                                                                      \
        });                                                                                                                    \
    }

/// @brief Macro to automatically register a deferred early hook installation
/// function for original hooks with specified logger.
/// @param logger_ The logger to be used during install.
/// @param name_ The name of the hook to be installed.
#define MAKE_EARLY_ORIG_HOOK_INSTALL(logger_, name_)                                                                           \
    __attribute((constructor)) void Hook_##name_##_Auto_Orig_Register() {                                                      \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Early, []() { \
            INSTALL_HOOK_ORIG(logger_, name_);                                                                                 \
        });                                                                                                                    \
    }

/// @brief Macro to automatically register a deferred early direct hook
/// installation function with specified logger.
/// @param logger_ The logger to be used during install.
/// @param name_ The name of the hook to be installed.
/// @param addr_ The address that should be hooked.
#define MAKE_EARLY_DIRECT_HOOK_INSTALL(logger_, name_, addr_)                                                                  \
    __attribute((constructor)) void Hook_##name_##_Auto_Register() {                                                           \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Early, []() { \
            INSTALL_HOOK_DIRECT(logger_, name_, addr_);                                                                        \
        });                                                                                                                    \
    }

/// @brief Macro to automatically register a deferred late hook installation
/// function.
/// @param name_ The name of the hook to be installed.
#define MAKE_LATE_HOOK_INSTALL_WITH_AUTOLOGGER(name_)                                                                         \
    __attribute((constructor)) void Hook_##name_##_Auto_Register() {                                                          \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Late, []() { \
            INSTALL_HOOK(::__AutoHooksInternal__::DeferredHooks::logger, name_);                                              \
        });                                                                                                                   \
    }

/// @brief Macro to automatically register a deferred late hook installation
/// function for original hooks.
/// @param name_ The name of the hook to be installed.
#define MAKE_LATE_ORIG_HOOK_INSTALL_WITH_AUTOLOGGER(name_)                                                                    \
    __attribute((constructor)) void Hook_##name_##_Auto_Orig_Register() {                                                     \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Late, []() { \
            INSTALL_HOOK_ORIG(::__AutoHooksInternal__::DeferredHooks::logger, name_);                                         \
        });                                                                                                                   \
    }

/// @brief Macro to automatically register a deferred late direct hook
/// installation function.
/// @param name_ The name of the hook to be installed.
/// @param addr_ The address that should be hooked.
#define MAKE_LATE_DIRECT_HOOK_INSTALL_WITH_AUTOLOGGER(name_, addr_)                                                           \
    __attribute((constructor)) void Hook_##name_##_Auto_Register() {                                                          \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Late, []() { \
            INSTALL_HOOK_DIRECT(::__AutoHooksInternal__::DeferredHooks::logger, name_, addr_);                                \
        });                                                                                                                   \
    }

/// @brief Macro to automatically register a deferred late hook installation
/// function with specified logger.
/// @param logger_ The logger to be used during install.
/// @param name_ The name of the hook to be installed.
#define MAKE_LATE_HOOK_INSTALL(logger_, name_)                                                                                \
    __attribute((constructor)) void Hook_##name_##_Auto_Register() {                                                          \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Late, []() { \
            INSTALL_HOOK(logger_, name_);                                                                                     \
        });                                                                                                                   \
    }

/// @brief Macro to automatically register a deferred late hook installation
/// function for original hooks with specified logger.
/// @param logger_ The logger to be used during install.
/// @param name_ The name of the hook to be installed.
#define MAKE_LATE_ORIG_HOOK_INSTALL(logger_, name_)                                                                           \
    __attribute((constructor)) void Hook_##name_##_Auto_Orig_Register() {                                                     \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Late, []() { \
            INSTALL_HOOK_ORIG(logger_, name_);                                                                                \
        });                                                                                                                   \
    }

/// @brief Macro to automatically register a deferred late direct hook
/// installation function with specified logger.
/// @param logger_ The logger to be used during install.
/// @param name_ The name of the hook to be installed.
/// @param addr_ The address that should be hooked.
#define MAKE_LATE_DIRECT_HOOK_INSTALL(logger_, name_, addr_)                                                                  \
    __attribute((constructor)) void Hook_##name_##_Auto_Register() {                                                          \
        ::__AutoHooksInternal__::DeferredHooks::addInstallFunc(::__AutoHooksInternal__::DeferredHooks::HookType::Late, []() { \
            INSTALL_HOOK_DIRECT(logger_, name_, addr_);                                                                       \
        });                                                                                                                   \
    }

/// @brief Macro to automatically install a hook on dlopen with a logger.
#ifdef INSTALL_HOOK_DIRECT
#define INSTALL_HOOK_ON_DLOPEN_WITH_AUTOLOGGER(name_)                                                                              \
    __attribute((constructor)) void Hook_##name_##_Dlopen_Install() {                                                              \
        INSTALL_HOOK_DIRECT(::__AutoHooksInternal__::DeferredHooks::logger, name_,                                                 \
                            reinterpret_cast<void*>(::getRealOffset(Hook_##name_::addr())));                                       \
    }
#else
#define INSTALL_HOOK_ON_DLOPEN_WITH_AUTOLOGGER(name_)                        \
    __attribute((constructor)) void Hook_##name_##_Dlopen_Install() {        \
        INSTALL_HOOK(::__AutoHooksInternal__::DeferredHooks::logger, name_); \
    }
#endif

/// @brief Macro to automatically install a direct hook on dlopen with a logger.
#define INSTALL_DIRECT_HOOK_ON_DLOPEN_WITH_AUTOLOGGER(name_, addr_)                        \
    __attribute((constructor)) void Hook_##name_##_Dlopen_Direct_Install() {               \
        INSTALL_HOOK_DIRECT(::__AutoHooksInternal__::DeferredHooks::logger, name_, addr_); \
    }

/// @brief Macro to automatically install an original hook on dlopen with a
/// logger.
#define INSTALL_ORIG_HOOK_ON_DLOPEN_WITH_AUTOLOGGER(name_)                        \
    __attribute((constructor)) void Hook_##name_##_Dlopen_Orig_Install() {        \
        INSTALL_HOOK_ORIG(::__AutoHooksInternal__::DeferredHooks::logger, name_); \
    }

/// @brief Macro to install a hook on dlopen with specified logger.
#ifdef INSTALL_HOOK_DIRECT
#define INSTALL_HOOK_ON_DLOPEN(logger_, name_)                                                                                 \
    __attribute((constructor)) void Hook_##name_##_Dlopen_Install() {                                                          \
        INSTALL_HOOK_DIRECT(logger_, name_, reinterpret_cast<void*>(::getRealOffset(Hook_##name_::addr())));                   \
    }
#else
#define INSTALL_HOOK_ON_DLOPEN(logger_, name_)                         \
    __attribute((constructor)) void Hook_##name_##_Dlopen_Install() { \
        INSTALL_HOOK(logger_, name_);                                  \
    }
#endif

/// @brief Macro to install a direct hook on dlopen with specified logger.
#define INSTALL_DIRECT_HOOK_ON_DLOPEN(logger, name_, addr_)                  \
    __attribute((constructor)) void Hook_##name_##_Dlopen_Direct_Install() { \
        INSTALL_HOOK_DIRECT(logger, name_, addr_);                           \
    }

/// @brief Macro to install an original hook on dlopen with specified logger.
#define INSTALL_ORIG_HOOK_ON_DLOPEN(logger, name_)                         \
    __attribute((constructor)) void Hook_##name_##_Dlopen_Orig_Install() { \
        INSTALL_HOOK_ORIG(logger, name_);                                  \
    }

/// @brief Macro to install all registered early hooks.
#define INSTALL_EARLY_HOOKS() ::__AutoHooksInternal__::DeferredHooks::installHooks(::__AutoHooksInternal__::DeferredHooks::HookType::Early)

/// @brief Macro to install all registered late hooks.
#define INSTALL_LATE_HOOKS() ::__AutoHooksInternal__::DeferredHooks::installHooks(::__AutoHooksInternal__::DeferredHooks::HookType::Late)

/// @brief Returns the number of early hook installation functions that have
/// been registered.
#define EARLY_HOOK_COUNT ::__AutoHooksInternal__::DeferredHooks::getHookCount(::__AutoHooksInternal__::DeferredHooks::HookType::Early)

/// @brief Returns the number of late hook installation functions that have been
/// registered.
#define LATE_HOOK_COUNT ::__AutoHooksInternal__::DeferredHooks::getHookCount(::__AutoHooksInternal__::DeferredHooks::HookType::Late)

}  // namespace

/// Early Hooks
namespace {

// Defines a hook to a manually found address or il2cpp method.
// addr_info must be in parentheses, and can either be an expression that produces a pointer,
// or a find_class_info, method name, and boolean flag if an instance method.
// If given an il2cpp method, it will search for one that matches the given return type and parameters.
#define MAKE_EARLY_HOOK(name_, addr_info, ret_type, ...)                                                             \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                       \
        using func_t = ret_type (*)(__VA_ARGS__);                                                              \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::detail::resolve_addr<func_t>{} addr_info, ret_type, __VA_ARGS__) \
    };                                                                                                         \
MAKE_EARLY_HOOK_INSTALL_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

// Defines a hook to a method with metadata provided through i2c::metadata_getter.
// Will automatically cast overloads, check types, and detect static/instance methods, based on the given return type and parameters.
// Generic methods cannot be hooked with this macro.
#define MAKE_EARLY_HOOK_MATCH(name_, method, ret_type, ...)                                                                            \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                                         \
        static constexpr auto cast_test = []<typename T>() { return requires { static_cast<T>(method); }; };                     \
        using func_t = ret_type (*)(__VA_ARGS__);                                                                                \
        using cast_t = ::i2c::detail::method_check<cast_test, func_t>::type;                                                    \
        static_assert(cast_test.operator()<cast_t>(), "Hook method signature does not match!");                                  \
        static_assert(::i2c::detail::match_hookable<static_cast<cast_t>(method)>, "Method cannot be hooked!");                  \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::metadata_getter<static_cast<cast_t>(method)>::method_info(), ret_type, __VA_ARGS__) \
    };                                                                                                                           \
MAKE_EARLY_HOOK_INSTALL_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

// Defines a hook to a manually found address or il2cpp method.
// addr_info must be in parentheses, and can either be an expression that produces a pointer,
// or a find_class_info, method name, and boolean flag if an instance method.
// If given an il2cpp method, it will search for one that matches the given return type and parameters.
#define MAKE_EARLY_ORIG_HOOK(name_, addr_info, ret_type, ...)                                                             \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                       \
        using func_t = ret_type (*)(__VA_ARGS__);                                                              \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::detail::resolve_addr<func_t>{} addr_info, ret_type, __VA_ARGS__) \
    };                                                                                                         \
MAKE_EARLY_ORIG_HOOK_INSTALL_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

// Defines a hook to a method with metadata provided through i2c::metadata_getter.
// Will automatically cast overloads, check types, and detect static/instance methods, based on the given return type and parameters.
// Generic methods cannot be hooked with this macro.
#define MAKE_EARLY_ORIG_HOOK_MATCH(name_, method, ret_type, ...)                                                                            \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                                         \
        static constexpr auto cast_test = []<typename T>() { return requires { static_cast<T>(method); }; };                     \
        using func_t = ret_type (*)(__VA_ARGS__);                                                                                \
        using cast_t = ::i2c::detail::method_check<cast_test, func_t>::type;                                                    \
        static_assert(cast_test.operator()<cast_t>(), "Hook method signature does not match!");                                  \
        static_assert(::i2c::detail::match_hookable<static_cast<cast_t>(method)>, "Method cannot be hooked!");                  \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::metadata_getter<static_cast<cast_t>(method)>::method_info(), ret_type, __VA_ARGS__) \
    };                                                                                                                           \
MAKE_EARLY_ORIG_HOOK_INSTALL_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

}

/// Late Hooks
namespace {

// Defines a hook to a manually found address or il2cpp method.
// addr_info must be in parentheses, and can either be an expression that produces a pointer,
// or a find_class_info, method name, and boolean flag if an instance method.
// If given an il2cpp method, it will search for one that matches the given return type and parameters.
#define MAKE_LATE_HOOK(name_, addr_info, ret_type, ...)                                                             \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                       \
        using func_t = ret_type (*)(__VA_ARGS__);                                                              \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::detail::resolve_addr<func_t>{} addr_info, ret_type, __VA_ARGS__) \
    };                                                                                                         \
MAKE_LATE_HOOK_INSTALL_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

// Defines a hook to a method with metadata provided through i2c::metadata_getter.
// Will automatically cast overloads, check types, and detect static/instance methods, based on the given return type and parameters.
// Generic methods cannot be hooked with this macro.
#define MAKE_LATE_HOOK_MATCH(name_, method, ret_type, ...)                                                                            \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                                         \
        static constexpr auto cast_test = []<typename T>() { return requires { static_cast<T>(method); }; };                     \
        using func_t = ret_type (*)(__VA_ARGS__);                                                                                \
        using cast_t = ::i2c::detail::method_check<cast_test, func_t>::type;                                                    \
        static_assert(cast_test.operator()<cast_t>(), "Hook method signature does not match!");                                  \
        static_assert(::i2c::detail::match_hookable<static_cast<cast_t>(method)>, "Method cannot be hooked!");                  \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::metadata_getter<static_cast<cast_t>(method)>::method_info(), ret_type, __VA_ARGS__) \
    };                                                                                                                           \
MAKE_LATE_HOOK_INSTALL_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

// Defines a hook to a manually found address or il2cpp method.
// addr_info must be in parentheses, and can either be an expression that produces a pointer,
// or a find_class_info, method name, and boolean flag if an instance method.
// If given an il2cpp method, it will search for one that matches the given return type and parameters.
#define MAKE_LATE_ORIG_HOOK(name_, addr_info, ret_type, ...)                                                             \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                       \
        using func_t = ret_type (*)(__VA_ARGS__);                                                              \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::detail::resolve_addr<func_t>{} addr_info, ret_type, __VA_ARGS__) \
    };                                                                                                         \
MAKE_LATE_ORIG_HOOK_INSTALL_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

// Defines a hook to a method with metadata provided through i2c::metadata_getter.
// Will automatically cast overloads, check types, and detect static/instance methods, based on the given return type and parameters.
// Generic methods cannot be hooked with this macro.
#define MAKE_LATE_ORIG_HOOK_MATCH(name_, method, ret_type, ...)                                                                            \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                                         \
        static constexpr auto cast_test = []<typename T>() { return requires { static_cast<T>(method); }; };                     \
        using func_t = ret_type (*)(__VA_ARGS__);                                                                                \
        using cast_t = ::i2c::detail::method_check<cast_test, func_t>::type;                                                    \
        static_assert(cast_test.operator()<cast_t>(), "Hook method signature does not match!");                                  \
        static_assert(::i2c::detail::match_hookable<static_cast<cast_t>(method)>, "Method cannot be hooked!");                  \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::metadata_getter<static_cast<cast_t>(method)>::method_info(), ret_type, __VA_ARGS__) \
    };                                                                                                                           \
MAKE_LATE_ORIG_HOOK_INSTALL_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

}

/// Dlopen Hooks
namespace {

// Defines a hook to a manually found address or il2cpp method.
// addr_info must be in parentheses, and can either be an expression that produces a pointer,
// or a find_class_info, method name, and boolean flag if an instance method.
// If given an il2cpp method, it will search for one that matches the given return type and parameters.
#define MAKE_DLOPEN_HOOK(name_, addr_info, ret_type, ...)                                                             \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                       \
        using func_t = ret_type (*)(__VA_ARGS__);                                                              \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::detail::resolve_addr<func_t>{} addr_info, ret_type, __VA_ARGS__) \
    };                                                                                                         \
INSTALL_HOOK_ON_DLOPEN_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

// Defines a hook to a method with metadata provided through i2c::metadata_getter.
// Will automatically cast overloads, check types, and detect static/instance methods, based on the given return type and parameters.
// Generic methods cannot be hooked with this macro.
#define MAKE_DLOPEN_HOOK_MATCH(name_, method, ret_type, ...)                                                                            \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                                         \
        static constexpr auto cast_test = []<typename T>() { return requires { static_cast<T>(method); }; };                     \
        using func_t = ret_type (*)(__VA_ARGS__);                                                                                \
        using cast_t = ::i2c::detail::method_check<cast_test, func_t>::type;                                                    \
        static_assert(cast_test.operator()<cast_t>(), "Hook method signature does not match!");                                  \
        static_assert(::i2c::detail::match_hookable<static_cast<cast_t>(method)>, "Method cannot be hooked!");                  \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::metadata_getter<static_cast<cast_t>(method)>::method_info(), ret_type, __VA_ARGS__) \
    };                                                                                                                           \
INSTALL_HOOK_ON_DLOPEN_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

// Defines a hook to a manually found address or il2cpp method.
// addr_info must be in parentheses, and can either be an expression that produces a pointer,
// or a find_class_info, method name, and boolean flag if an instance method.
// If given an il2cpp method, it will search for one that matches the given return type and parameters.
#define MAKE_DLOPEN_ORIG_HOOK(name_, addr_info, ret_type, ...)                                                             \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                       \
        using func_t = ret_type (*)(__VA_ARGS__);                                                              \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::detail::resolve_addr<func_t>{} addr_info, ret_type, __VA_ARGS__) \
    };                                                                                                         \
INSTALL_ORIG_HOOK_ON_DLOPEN_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

// Defines a hook to a method with metadata provided through i2c::metadata_getter.
// Will automatically cast overloads, check types, and detect static/instance methods, based on the given return type and parameters.
// Generic methods cannot be hooked with this macro.
#define MAKE_DLOPEN_ORIG_HOOK_MATCH(name_, method, ret_type, ...)                                                                            \
    struct BS_HOOK_HIDDEN hook_##name_ {                                                                                         \
        static constexpr auto cast_test = []<typename T>() { return requires { static_cast<T>(method); }; };                     \
        using func_t = ret_type (*)(__VA_ARGS__);                                                                                \
        using cast_t = ::i2c::detail::method_check<cast_test, func_t>::type;                                                    \
        static_assert(cast_test.operator()<cast_t>(), "Hook method signature does not match!");                                  \
        static_assert(::i2c::detail::match_hookable<static_cast<cast_t>(method)>, "Method cannot be hooked!");                  \
        __INTERNAL_HOOK_STRUCT(name_, ::i2c::metadata_getter<static_cast<cast_t>(method)>::method_info(), ret_type, __VA_ARGS__) \
    };                                                                                                                           \
INSTALL_ORIG_HOOK_ON_DLOPEN_WITH_AUTOLOGGER(name_); \
    ret_type hook_##name_::hook_m_##name_(__VA_ARGS__)

}
